name: python ci

on:
  push:
    branches:
      - main

jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v2

      - name: set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install dependencies
        run: 
          python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: installing flake8
        run: pip install flake8
      
      - name: run flake8
        run: flake8 app.py

      - name: installing safety
        run: pip install safety
      
      - name: run safety
        env:
          SAFETY_API_KEY: ${{ secrets.cisafetyapi }}
        run: safety scan -r requirements.txt --no-patch

      - name: installing bandit
        run: pip install bandit

      - name: run bandit
        run: bandit -r app.py
      
   
